services:
  trino:
    image: trinodb/trino
    container_name: trino
    restart: unless-stopped
    ports:
      - 8080:8080

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTFRES_DB: test
    ports:
      - "5432:5432"

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  # networks:
  # volumes:
    # postgres_data:
    # cassandra_data:
    # redis_data: